#!/bin/sh

DIR=`dirname $0`
SECDVM=$DIR/secd
COMPILER=$DIR/scm2secd.secd
REPLSRC=$DIR/repl.scm
REPL=$DIR/repl.secd

die () {
    echo $@ >&2
    exit 1
}

interp () {
    RLWRAP="`which rlwrap`"
    [ "$RLWRAP" ] && RLWRAP="$RLWRAP -r -q \"\\\"\" "
    exec $RLWRAP $SECDVM $REPL
}

compile () {
    case "$1" in
      *.scm) ;;
      *) die "Error: file $1 must have .scm extension" ;;
    esac

    SRC="$1"
    DST="${1/scm/secd}"

    # backup destination if needed
    [ -e "$DST" ] && mv "$DST" "$DST~"
    $SECDVM $COMPILER <$SRC >"${DST}.1" || die "Error: compilation failed"
    mv "${DST}.1" $DST
    exit 0
}

test -f "$REPL" || {
    export REPL="$DIR/../share/secdscheme/secd/repl.secd"
    test -f "$REPL" || die "repl.secd not found"
}

# is there the secd interpreter?
[ -x $SECDVM ] || die "$SECDVM not found"

if [ "$1" = '-c' ] ; then
    echo ";; compiling..."
    shift; compile "$@"
fi

interp
